### ISSUE TITLE
Format of Table in CustomEffects Page is incorrect

### ISSUE THREAD

**Issue by dellis1972** [MonoGame/docs.monogame.github.io#19]
see https://docs.monogame.net/articles/content_pipeline/custom_effects.html#effect-writing-tips.

The formatting of the Table is the custom_effects page does not show up correctly. 
<img width="1496" alt="Screenshot 2024-05-27 at 22 08 01" src="https://github.com/MonoGame/docs.monogame.github.io/assets/810617/33126cbc-319f-446b-8114-91c43b2b7d9b">

**Comment by JakeLegendXIII** [comment]
I have created PR #26 to resolve this issue. Please let me know if there are any questions or concerns!

**Comment by dellis1972** [comment]
@JakeLegendXIII thanks for fixing this
