### ISSUE TITLE
XML with MGCB example link is "half" broken

### ISSUE THREAD

**Issue by n-eit** [MonoGame/docs.monogame.github.io#32]
Hello, 

I saw a little detail on the page concerning the use of XML file with [MGCB editor](https://docs.monogame.net/articles/content_pipeline/using_mgcb_editor.html#text-eg-xml).

The external link provided (for an example on how to use XML) redirect to a website where all the images are unavailable. 

![image](https://github.com/user-attachments/assets/99c46394-f48a-4063-a58f-0241de8c2825)

Instead, can you redirect to [this website](https://www.codeproject.com/Articles/1189981/Getting-Started-with-MonoGame-using-XML) for example?

![image](https://github.com/user-attachments/assets/8b1d17b7-e8f1-442f-83e6-95c08c601f7e)

I can update that link using a pull request, I already prepared a local branch, but got a permission denied when trying to push it.

**Comment by SimonDarksideJ** [comment]
Thanks for pointing this out, not sure how/why DZone mucked up all the image links.

For safety, I've updated the link to go back to the original source on the authors blog :D
https://darkgenesis.zenithmoon.com/getting-started-with-monogame-using-xml.html
