### ISSUE TITLE
Remove WindowsPhone references

### ISSUE THREAD

**Issue by dellis1972** [MonoGame/docs.monogame.github.io#61]
https://github.com/MonoGame/docs.monogame.github.io/blob/main/articles/getting_to_know/whatis/graphics/index.md

```
A configurable effect is an optimised rendering effect designed for Windows Phone. A configurable effect is created using a built-in object with options for user configuration.
```

maybe something like

```
MonoGame ships with a number of built in effects. These effects have properties so you can use to change behaviour or switch features on or off. 
```

Since its talking about things like `BasicEffect` and `SkinnedEffect`.

While there , what is a "configurable effect" ? I would think "Build In Effects" or something like that would make more sense. Since these are built-in to MonoGame.

**Comment by SimonDarksideJ** [comment]
Darn it, I thought I got all of them, it was something I was on the watch for.

But we have had other discussions about graphics profiles and whether or not they are even relevant today
